testheroku/mypage/urls.py
from django.urls import path
from .views import index, exclude_images

app_name = 'mypage'

urlpatterns = [
    path('', index, name='index'),
    path('cleanimages/', exclude_images, name='exclude_images'),
]

testheroku/testheroku/urls.py
from __future__ import absolute_import, unicode_literals
from django.contrib import admin
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('', include('mypage.urls', namespace='mypage')),
    path('admin/', admin.site.urls),
]

# ##########################Media/Static
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

testheroku/mypage/models.py
from __future__ import absolute_import, unicode_literals
from django.db.models.signals import post_delete, post_save
from django.db import models
from django.dispatch import receiver
from django.utils import timezone


class MyImage(models.Model):
    name = models.CharField('Name', max_length=80, unique=True)
    image = models.ImageField(
        upload_to='myimage/images', verbose_name='Image',
        null=False, blank=False)
    created_at = models.DateTimeField('Create at', null=True, auto_now_add=True)


    class Meta:
        verbose_name = 'My Image'
        verbose_name_plural = 'My Images'
        ordering = ['-created_at']

    def __str__(self):
        return self.name


def delete_all(time_ago="all"):
    if time_ago == "all":
        time_ago = timezone.now()
    ok = MyImage.objects.filter(created_at__lte=time_ago).delete()


# Signal to delete the file of image when your register in the database will be deleted.
@receiver(post_delete, sender=MyImage)
def image_post_delete_handler(sender, **kwargs):
    listingImage = kwargs['instance']
    storage, path = listingImage.image.storage, listingImage.image.path
    storage.delete(path)

testheroku/mypage/forms.py
from django import forms
from .models import MyImage


class MyImageForm(forms.ModelForm):
    name = forms.CharField(label='Name', max_length=128)
    image = forms.ImageField()

    class Meta:
        model = MyImage
        fields = ['name', 'image']

testheroku/mypage/views.py
from __future__ import absolute_import, unicode_literals
from django.urls import reverse
from django.shortcuts import render, redirect
from .forms import MyImageForm
from .models import MyImage, delete_all
import os
from django.conf import settings

def index(request):
    context = {}
    ok = False
    myimages = MyImage.objects.order_by('-created_at')
    if myimages:
        path = os.path.join(settings.MEDIA_ROOT, str(myimages[0].image))
        ok = os.path.isfile(path)
        if not ok:
            exclude_images(request)
            myimages = MyImage.objects.order_by('-created_at')
    context['myimages'] = myimages
    if request.method == 'POST':
        form = MyImageForm(request.POST, request.FILES)
        if form.is_valid():
            form.save(commit=True)
            if len(myimages) >= 3:
                id = myimages[len(myimages) - 1].id
                MyImage.objects.get(pk=id).delete()
            return redirect(reverse('mypage:index'))
        else:
            context['messages'] = form.errors
    context['form'] = MyImageForm()
    return render(request, 'mypage/index.html', context)


def exclude_images(request):
    context = {}
    ok = delete_all()
    if ok:
        myimages = {}
    else:
        myimages = MyImage.objects.order_by('-created_at')
    context['myimages'] = myimages
    context['form'] = MyImageForm()
    return render(request, 'mypage/index.html', context)

testheroku/mypage/templates/mypage/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <!-- Carga do css -->
    {% load static %}
    {% block stylesheet %}
        <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
    {% endblock %}

    <title>My Page-Whitenoise</title>
</head>

<body>
    <h1>Welcome to my <img src="{% static 'img/heroku.png' %}" alt="Heroku" width="42" height="42"> first page!</h1>

    <h2>Add Image</h2>
    <form id="mypage_form" method="post" enctype="multipart/form-data" action="{% url 'mypage:index' %}" >
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="submit" value="Image Add" />
    </form>

    {% if messages %}
        {% for message in messages.values %}
                <strong>{{ message }}</strong>
        {% endfor %}
    {% endif %}

    {% if myimages %}
        <h2> Showing to last three included images. </h2>
        <h6> All images have been reduced to 5% of their size. </h6>
        {% for i in myimages %}
            {{i.name}}<br />
            <div>
                <img src="{{ i.image.url }}" alt="{{ course.name }}" width="5%" />
            </div>
            <br>
        {% empty %}
            <p>No Images at moment - Images are deleted by expired free dyno Heroku.</p>
        {% endfor %}
        <br /><a href="{% url 'mypage:exclude_images' %}" class="button">"Please click here to clean your images"</a><br />
    {% else %}
        <br /><p>No Images at moment - Images are deleted by expired free dyno Heroku.</p><br />
    {% endif %}

</br>

</html>